# Generated by Django 4.0.4 on 2022-05-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('login', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19)),
                ('slug', models.SlugField(max_length=128)),
                ('marque', models.CharField(max_length=128)),
                ('administrateur', models.CharField(max_length=20)),
                ('zone', models.CharField(max_length=50)),
                ('configuration', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='computerapp/images')),
            ],
        ),
        migrations.CreateModel(
            name='Routeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19)),
                ('slug', models.SlugField(max_length=128)),
                ('marque', models.CharField(max_length=128)),
                ('administrateur', models.CharField(max_length=20)),
                ('zone', models.CharField(max_length=50)),
                ('configuration', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='static/compterapp/images')),
            ],
        ),
    ]
