# Generated by Django 4.1.7 on 2023-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0002_personnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="prenom",
            field=models.CharField(default="", max_length=10),
        ),
    ]
