# Generated by Django 4.0.4 on 2022-05-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0002_alter_commu_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeur',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
