# Generated by Django 4.1.7 on 2023-05-05 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0003_personnel_prenom"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="mach",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run windows"),
                    ("Mac", "MAc - Run MacOS"),
                    ("Serveur", "Serveur - Simple Server to deploy virtual machines"),
                    ("Switch", "Switch - To maintains and connect servers"),
                ],
                default="PC",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="maintenaceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 5, 9, 1, 42, 57347)
            ),
        ),
    ]
