# Generated by Django 4.0.4 on 2022-06-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0004_compte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compte',
        ),
    ]
