# Generated by Django 4.1.7 on 2023-05-11 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0004_machine_mach_machine_maintenacedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenaceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 11, 9, 55, 57, 87190)
            ),
        ),
    ]
