# Generated by Django 4.1.7 on 2023-05-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0005_delete_compte"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
