# Generated by Django 4.1.7 on 2023-05-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_compte"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=19)),
                ("slug", models.SlugField(max_length=128)),
                ("marque", models.CharField(max_length=128)),
                ("administrateur", models.CharField(max_length=20)),
                ("zone", models.CharField(max_length=50)),
                ("configuration", models.TextField(blank=True)),
                ("detail", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Routeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=19)),
                ("slug", models.SlugField(max_length=128)),
                ("marque", models.CharField(max_length=128)),
                ("administrateur", models.CharField(max_length=20)),
                ("zone", models.CharField(max_length=50)),
                ("configuration", models.TextField(blank=True)),
                ("detail", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
            ],
        ),
    ]
